### ISSUE TITLE
Feature request: move scroll down to show new opened tab

### ISSUE THREAD

**Issue by roman4e** [Croydon/vertical-tabs-reloaded#71] opened 2016-12-12 22:11 UTC
Please make the tab bar do little scroll down to make newly opened tab visible. Because the impression that nothing has opened.

Add-on version: latest
Firefox version: 50
OS + OS-Version: Linux Mint 18
Other tab + user interface related add-ons:

**Comment by mbaz** [comment] 2016-12-12 22:17
Duplicate of #53

**Closed** 2016-12-13 19:55 UTC
Labels: org:duplicate
