### ISSUE TITLE
Conflict Firefox 50.0a1 64bit in e10s vertical-tabs-reloaded and Multiple Tab Handler, e10s disabled most thing will work again

### ISSUE THREAD

**Issue by loa11** [Croydon/vertical-tabs-reloaded#56] opened 2016-07-08 21:44 UTC
Add-on version:070
Firefox version:50.0a1 64bit in e10s
OS + OS-Version:Windows 7 64bit SP1
Other tab + user interface related add-ons: Multiple Tab Handler use latest dev version.

In e10s mode most tabs functions from  Multiple Tab Handler will not work like shift+left click select multiple tabs, or Ctrl+left click close tab etc 
https://github.com/piroor/multipletab/issues/122

When you switch of e10s seems most conflicts were removed.

**Comment by Croydon** [comment] 2016-07-08 22:06
Duplicate of #49.

**Closed by Croydon** 2016-07-08 22:06 UTC

**Comment by loa11** [comment] 2016-07-08 22:25
Its working but conflicting when,  e10s is disabled everything is working like it should its not the same bug, please this is not the duplicate of #49.

**Comment by loa11** [comment] 2016-07-08 22:57
Piro is writer of MTH he is also father of legendary TBE he is very cleaver guy, he could sort this conflict in a matter of minutes.

 Could you add this option to vertical-tabs-reloaded

Duplicate tab
Select similar tabs
Close tabs to the TOP
Close similar tabs
Close other similar tabs
Close all tabs

Also shift +mouse left click would select multiple tabs in order to move them or close them also with ctrl+left click would close tab
