### ISSUE TITLE
Feature Request: Use Firefox theme

### ISSUE THREAD

**Issue by DG094** [Croydon/vertical-tabs-reloaded#290] opened 2024-06-27 15:16 UTC
Add-on version: 0.13.1
Firefox version: 127.0.2 (64-bit)
OS + OS-Version: Linux, Debian, XFCE4 desktop
Other tab + user interface related add-ons: New Tab Override

Hi.

I've just installed this after discovering that the original Vertical Tabs extension is no longer supported and may be the cause of crashes I was experiencing when closing multiple tabs.

The original followed the browser theme and blended in with the rest of the UI; the context menu was the same as the default vertical tabs context menu, too.

Would it be possible for you to give the options of using the browser theme and context menu?

Kind regards.

**Comment by Croydon** [comment] 2024-06-27 17:52
Thanks for the feedback. I am going to close this as a duplicate of #138 and #205

**Closed by Croydon** 2024-06-27 17:52 UTC
