### ISSUE TITLE
Current tab is highlighted when pressing laptop fn keys 

### ISSUE THREAD

**Issue by fbruetting** [Croydon/vertical-tabs-reloaded#48] opened 2016-05-29 16:00 UTC
Add-on version: 0.6.1
Firefox version: 46.0.1
OS + OS-Version: Fedora 23

When pressing brighter/darker/quieter/louder/mute etc. the current tab entry gets highlighted.

**Comment by Croydon** [comment] 2017-04-09 16:22
@fbruetting Could you please retest with the latest add-on and Firefox version?

**Comment by Croydon** [comment] 2017-05-01 00:07
Closing because I can't reproduce this. 
Also closing because of the heavy refactoring upcoming. If this ever was a bug of VTR it will be gone after #13 is fixed.

**Closed by Croydon** 2017-05-01 00:07 UTC
Labels: org:needs validation/discussion
