### ISSUE TITLE
Both horizontal and vertical tabs are showing after latest update

### ISSUE THREAD

**Issue by jacqueskotze** [Croydon/vertical-tabs-reloaded#153] opened 2017-11-15 23:54 UTC
Add-on version: 0.9.1
Firefox version: 57.0 (64-bit)
OS + OS-Version: Win 10 Pro, 1703 Build 15063.726
Other tab + user interface related add-ons: AdBliock PLus, Avast Online Security, Evernote Clipper, LastPass

![image](https://user-images.githubusercontent.com/3579573/32866324-0dd07288-ca5f-11e7-91c6-9f555b78351b.png)

Today both Firefox and VTR updated and I'm left with both the verital and horizontal tab on now at the same time, I can toggle the vertical tabs on and off and left to right, but the horizontal tabs are not going away as it used to. Needless to say I have removed VTR and added it back in again and restarted my machine, but still the same. 
Any ideas on how to fix this will be greatly appreciated as I typically have a few hundred tabs open and having them showing both at the top and bottom is going to get really ugly.

**Comment by voxadam** [comment] 2017-11-16 01:29
https://github.com/Croydon/vertical-tabs-reloaded/issues/13#issuecomment-344681263

**Comment by Croydon** [comment] 2017-11-16 12:22
Please use the search before reporting issues.

This is a duplicate of #128.

**Closed by Croydon** 2017-11-16 12:22 UTC
