### ISSUE TITLE
Can't select multiple tabs (to bookmark them)

### ISSUE THREAD

**Issue by Mr-Personality** [Croydon/vertical-tabs-reloaded#254] opened 2020-09-26 15:20 UTC
I had been trying to find some way to select multiple tabs so I can bookmark them. Then I discovered that you can actually do this in Firefox (by holding down Ctrl). But not with VTR, it seems?

Please could you support selecting multiple bookmarks? I have a bad habit of allowing a large number of tabs to build up, so I need to get into the habit of tidying tabs away by selecting and bookmarking them. And if I have to do it one tab at a time, it's very tedious!

Add-on version: 0.13.1
Firefox version: 81.0
OS + OS-Version: Win7 x64
Other tab + user interface related add-ons: none

**Comment by Croydon** [comment] 2020-09-27 03:34
This is on the roadmap, but I can't promise that it will land anytime soon

Duplicate of #190

**Closed by Croydon** 2020-09-27 03:34 UTC

**Comment by Mr-Personality** [comment] 2020-09-27 14:26
Thanks, Croydon!

I hope you can add it soon. I'm trying to keep my tabs really tidy now, so this function is important to me. I may have to temporarily stop using VTR until this gets implemented.

**Comment by Mr-Personality** [comment] 2020-09-29 11:01
Please could I ask, do you have a "what's new" page so I can keep an eye on new releases/features?

**Comment by Croydon** [comment] 2020-09-29 11:21
If you open the VTR settings, you have a `Show update news` button at the very top. This page will also open automatically if VTR updates in your browser

You could also use the `Release only` watch feature of GitHub

**Comment by Mr-Personality** [comment] 2020-09-29 16:13
Thanks! And thanks for the excellent add-on.
