### ISSUE TITLE
other tabs disappear when arranging tabs (dark and light theme)

### ISSUE THREAD

**Issue by jonasflint** [Croydon/vertical-tabs-reloaded#51] opened 2016-06-08 14:15 UTC
This is kind of weird, but when arranging tabs the other tabs strait up "disappear" while dragging until the tab is placed.  Makes it hard to gage where you are placing the tab...

Add-on version:
Firefox version:
OS + OS-Version:

**Comment by Croydon** [comment] 2016-06-08 14:37
@jonasflint Can you please provide the information what VTR version, what Firefox version and what OS + OS version you are using? It is there as an issue template for a reason :) 

According to the title I am assuming you can't reproduce this behaviour with the other themes?

**Comment by jonasflint** [comment] 2016-06-09 16:19
yes sorry about that. 
Add-On Version: 0.6.2
Firefox Version: 46.0.1
Mac OSX  El Capitan 10.11.5

**Comment by mbaz** [comment] 2016-06-13 00:25
This used to happen to me, but doesn't seem to anymore with version 0.6.2.

**Comment by Croydon** [comment] 2016-06-13 00:29
@jonasflint @mbaz Any chance that you two are using Tab Mix Plus?

**Comment by mbaz** [comment] 2016-06-13 01:50
No, I'm not using it.

**Comment by jonasflint** [comment] 2016-06-13 20:35
I am using tab mix plus

**Comment by Croydon** [comment] 2016-06-14 21:57
@jonasflint Do you use Tab Mix Plus v0.5.0 or newer? There will be problems if you use an older version.
If you should use v0.5.0 or newer: Do you have any other add-ons installed that have anything to do with Tabs or which modify the user interface of Firefox?

**Comment by jonasflint** [comment] 2016-06-16 14:33
No, not really. I'm using Tab Mix Plus v.0.5.0

**Comment by Croydon** [comment] 2017-02-07 20:57
@jonasflint If you are still using VTR it would be nice to know if you can still reproduce this with the current versions of FF, VTR and Tab Mix Plus :)

**Comment by Croydon** [comment] 2017-04-09 16:37
@mbaz Can you still reproduce this issue with current versions of VTR and Firefox?

I'm closing this soon if I don't get more feedback.

**Comment by mbaz** [comment] 2017-04-10 15:49
@Croydon Nope -- this bug stopped happening with v0.6.2.

**Comment by Croydon** [comment] 2017-04-10 16:11
@mbaz Awesome, thanks.

**Closed by Croydon** 2017-04-10 16:11 UTC
Labels: org:needs validation/discussion
