### ISSUE TITLE
Close button shown trice with dark theme

### ISSUE THREAD

**Issue by alexander255** [Croydon/vertical-tabs-reloaded#35] opened 2016-04-01 10:40 UTC
I tried to switch to the dark theme, but I think you're missing some image clipping with this theme:

![Screenshot](https://cloud.githubusercontent.com/assets/246386/14204734/85585bc2-f806-11e5-9ef9-8d259621fdae.png)

Vertical Tabs Reloaded 0.5.0
Firefox 46.0b2, Linux 4.4, x86_64

**Comment by yafp** [comment] 2016-04-01 12:16
I can reproduce that with VTR 0.5.0 using the dark theme (FF 45 on Linux).

**Comment by Croydon** [comment] 2016-04-01 23:37
I can confirm this as well on my Fedora machine, but not on my Windows setup.
Seems to be Linux only.

This is a follow up problem of #26. I'm wondering if @Keith94 would be willing to look into that once again? :smile:

**Comment by Keith94** [comment] 2016-04-02 02:33
@Croydon Well I don't have a Linux environment to reproduce this in, so I'm not entirely sure how to fix it. I played around with `-moz-image-region` to get a specific image for the different attributes. Maybe it will work for the 100% DPI setting...

```css
.tab-close-button {
    -moz-image-region: rect(0px, 20px, 20px, 0px) !important;
}
.tab-close-button:hover {
    -moz-image-region: rect(0px, 40px, 20px, 20px) !important;
}
.tab-close-button:active {
    -moz-image-region: rect(0px, 60px, 20px, 40px) !important;
}
```

**Comment by Keith94** [comment] 2016-04-02 03:49
This file from the source code contains additional rules for the Windows theme's close buttons: https://github.com/mozilla/gecko-dev/blob/master/toolkit/themes/windows/global/global.css#L326-L396

The default Linux theme is apparently using `background-image` rather than `list-style-image` for its close buttons, for what it's worth.
https://github.com/mozilla/gecko-dev/blob/master/toolkit/themes/linux/global/global.css#L311-L326

**Comment by alexander255** [comment] 2016-04-02 10:59
I can confirm that the style rules posted by @Keith94 fix the problem when added to the browser using stylish. :smile:

**Comment by Croydon** [comment] 2016-04-16 17:17
Fixed with the next update. Thank you all :)

**Closed** 2016-04-16 17:16 UTC
Labels: bug, help wanted, themes
