### ISSUE TITLE
Double Context Menus

### ISSUE THREAD

**Issue by brightghost** [Croydon/vertical-tabs-reloaded#214] opened 2018-12-11 19:34 UTC
Add-on version: 0.12.0
Firefox version: 60.0
OS + OS-Version: Windows 10 Enteprise1709 (Build 16299.785)
Other tab + user interface related add-ons:  None

When I right-click a tab, I get both the default context menu, and the extension's custom context menu, which makes the useful one quite difficult to use :) . I don't see any other issues opened for this so I presume it's correctly disabling the default context menu for others but not sure why this isn't working for me. I've tested with all other addons and my userChrome.css disabled and see the same behavior.I am also testing on a clean install of Firefox on a new machine (though all affected machines are linked to my FF account).  I have been seeing this behavior for quite a while (since shortly after the Quantum rollout if I recall), I don't think it's an issue introduced in a recent release. I also have been seeing this on my Linux system, will have to confirm when I am home if it's still present there.

<img width="237" alt="vert-tabs-context-menu-bug" src="https://user-images.githubusercontent.com/3108171/49825054-1c0f3a00-fd49-11e8-8eb5-22d7a93a3ac7.PNG">

**Comment by Croydon** [comment] 2018-12-12 06:51
Duplicate of #187 and I'm opening #187 again, as I can now reproduce it successfully.

**Closed by Croydon** 2018-12-12 06:51 UTC

**Comment by brightghost** [comment] 2018-12-13 02:00
Sorry, I did see that issue but from my read (and despite the title) it seemed to be a feature req. for the system context menu instead of the custom menu, not the double menu issue I'm seeing here. In any case I saw the news of the new API shortly after opening this, so thanks for your work on rolling it out.

**Comment by brightghost** [comment] 2019-03-17 16:54
I imagine this will still be rendered moot when the new API is implemented, but for now I want to share a solution to my issue for anyone else who may come across this: I was seeing both context menus because I had previously set `dom.event.contextmenu.enabled` to `False` in about:config to thwart annoying websites that try to disable the context menu. Apparently, this applies to extension views as well. The current custom menu is again working for me after reverting this to default.

**Comment by Croydon** [comment] 2019-03-18 02:35
@brightghost Thanks for sharing! I wasn't aware of this option
