### ISSUE TITLE
Auto hiding tabs in fullscreen does not work.

### ISSUE THREAD

**Issue by danwep** [Croydon/vertical-tabs-reloaded#44] opened 2016-05-20 22:34 UTC
Add-on version: 0.6.1
Firefox version: 46.0.1
OS + OS-Version: Linux, Debian testing[codename stretch]

The 'Hide tabs in fullscreen' option does not work. When placing Firefox
and/or a video in fullscreen, VTR does not hide. The only add-on
installed was VTR, in a new profile to avoid any conflicts with other
add-ons and/or user settings.

Thank You

**Comment by Croydon** [comment] 2016-05-20 23:06
@danwep What desktop environment do you use?

**Comment by danwep** [comment] 2016-05-20 23:27
xmonad[0]

[0] http://xmonad.org/

**Comment by danwep** [comment] 2016-06-15 23:19
An update. It seems to be a general issue with all?, at least with the few add-ons that have tried. That add/have an option for tabs on the side. Any video placed in fullscreen and the tabs on the side still show through.

Firefox's own sidebar does hide when placing videos in fullscreen mode.

Thank You

**Comment by Croydon** [comment] 2016-07-20 02:57
@danwep VTR and likely every other add-on you tried is using the sizemodechange event. So it **might** be a bug of Firefox in combination with your setup. (https://developer.mozilla.org/en-US/docs/Web/Events/sizemodechange)

Do you have any other DE where you can test it?

**Comment by Croydon** [comment] 2017-01-28 01:28
@danwep Please provide further feedback or I will need to close this issue.

**Comment by Croydon** [comment] 2017-02-03 05:33
Closed because missing information and can't be reproduced.

Feel free to comment on this issue if you are affected as well, till then -> invalid.

**Closed by Croydon** 2017-02-03 05:33 UTC
Labels: org:needs validation/discussion
