### ISSUE TITLE
Double click doesn't create a new tab anymore

### ISSUE THREAD

**Issue by giraffe17** [Croydon/vertical-tabs-reloaded#17] opened 2016-03-17 05:15 UTC
Happened after latest update

**Comment by Croydon** [comment] 2016-03-17 17:28
@giraffe17  Could you please provide more information? Where are you performing a double click?

**Comment by giraffe17** [comment] 2016-03-17 23:27
Double click on empty space of the side bar. Before the latest update it was similar to ctrl+t (new tab), now it does nothing.

**Comment by Croydon** [comment] 2016-03-19 13:35
I will look into it. Thanks for reporting :)

**Comment by yafp** [comment] 2016-03-30 06:24
@giraffe17: 
Opening a new empty tab by double-clicking the empty space below the last tab in my tabbar still works for me with 0.4.0 (on linux using FF 45)

**Comment by woj-tek** [comment] 2016-04-10 19:33
+1 for me - I've just went back to VTR (0.5.0) from tree-style-tab and it doesn't work, an while it was working previously (around version 0.3.x or 0.4.0) it's not working now. Would be awesome if this could be fixed :-)

**Comment by yafp** [comment] 2016-04-10 20:48
@woj-tek 
could be interesting i you have this issue with all themes or some just a specific one. For me with 0.5 it seems like i can reproduce that if i choose "None/Firefox default" in the addons pref while i can not reproduce it with the light theme for example.

**Comment by woj-tek** [comment] 2016-04-10 21:34
@yafp OK, because recently Mozilla pushed towards this new "themes" that were basically a picture splashed on the toolbar I've quit using those because of compatibility problems...

I've tried https://addons.mozilla.org/en-US/firefox/addon/ft-deepdark/ (btw. looks great :-) ) and... doubleclick on the empty area worked!

It's a bit weird that this issue is theme-specific...

I've opened similar issue for TST (#695) and the response was, that this was Fx fault... but when I think about it - maybe not exactly Fx but Firefox default theme?

**Comment by yafp** [comment] 2016-04-10 21:35
glad my feeling was right.

**Comment by detuur** [comment] 2016-05-11 20:56
Having the same problem in Firefox Developer Edition. Using the included dark theme.

**Comment by Croydon** [comment] 2017-04-09 16:40
Will be fixed for sure with #13.

**Closed** 2017-04-30 23:57 UTC
Labels: org:needs validation/discussion

**Comment by Croydon** [comment] 2017-04-30 23:59
I think this is a reasonable feature, so I implemented it in the WebExtension version of the add-on. Till now this was not a feature of VTR, but rather of Firefox and the theme.
Will take some time till this feature ships in a stable version of VTR. More info at #13.
