### ISSUE TITLE
Add option to condense tab sidebar by default (favicons only), expand it on hover

### ISSUE THREAD

**Issue by norseboar** [Croydon/vertical-tabs-reloaded#268] opened 2022-10-13 15:47 UTC
This is an idea for a feature.

Edge (yes, Edge!) has a really nice vertical tab feature out-of-the-box. One of the things they do is offer an "auto-collapse". In this mode, the tab sidebar only shows favicons. When you hover over the favicons, the sidepanel expands and behaves as-usual. It's a really nice way to give back some screen real-estate without sacrificing usability really. The below gif shows the interaction.

![collapse-tabbar](https://user-images.githubusercontent.com/906159/195643841-2392d086-f8d4-410d-837c-bcf5435179e5.gif)

Thoughts on adding an option for this? The contribution guidelines suggested I make an issue here to start a discussion, but I'm happy to implement it if y'all are good with it.

Add-on version: 0.13.1
Firefox version: 105.0.3
OS + OS-Version: Any?
Other tab + user interface related add-ons:

**Comment by Croydon** [comment] 2022-10-15 20:40
Duplicate of #135

**Closed by Croydon** 2022-10-15 20:40 UTC
