### ISSUE TITLE
Feature request: reload all tabs

### ISSUE THREAD

**Issue by hhmeyer** [Croydon/vertical-tabs-reloaded#172] opened 2018-03-15 09:17 UTC
Add-on version: 0.9.4
Firefox version: 59.0
OS + OS-Version: not relevant
Other tab + user interface related add-ons: none

It would be helpful to be able to reload all tabs of one window with a single mouse click like in Tree Style Tabs.
I like to have the tabs in vertical order, but I don't like the tree arrangement.

**Comment by Croydon** [comment] 2018-03-15 15:58
Please use the search before reporting issues.

This is a duplicate of #120

**Closed by Croydon** 2018-03-15 15:58 UTC
