### ISSUE TITLE
vertical tabs shoud disable horizontal tabs

### ISSUE THREAD

**Issue by notorand-it** [Croydon/vertical-tabs-reloaded#265] opened 2022-05-29 13:49 UTC
Add-on version: 0.13.1
Firefox version:  100.0.2
OS + OS-Version: Archlinux
Other tab + user interface related add-ons: 

Having vertical and horizontal tabs at the same time makes little sense.
If I install this extension is because I am not satisfied with horizontal tabs.
At least provide directions on how to disable them.

**Comment by Croydon** [comment] 2022-05-29 20:19
Duplicate of #128

As I have also written in [the description on AMO](https://addons.mozilla.org/en-US/firefox/addon/vertical-tabs-reloaded/) this is currently impossible from my side.

There is a hacky workaround with `userChrome.css`, but that is nothing that I would like to recommend to the average user or support.

**Closed by Croydon** 2022-05-29 20:19 UTC
