### ISSUE TITLE
Can't close tabs by left-click on x (sometines)

### ISSUE THREAD

**Issue by yafp** [Croydon/vertical-tabs-reloaded#188] opened 2018-05-02 11:26 UTC
Add-on version: 0.10.0
Firefox version: 59.0.2
OS + OS-Version: Ubuntu 16.04
Other tab + user interface related add-ons: none

**Issue**
It's not really reproducible for me so far, but it happens from times to times that i can not longer close tabs via mouse-click. If that happens i can still close tabs via CTRL+W.

**Workaround**
Restarting Firefox solved this issue

**Comment by Croydon** [comment] 2018-05-03 02:44
What kind of mouse-clicking?

Left click on the X?
Middle click on a tab?
Context menu option?

**Comment by yafp** [comment] 2018-05-03 08:35
Left click on the X

Haven't tried the other 2 options so far. Will do next time it happens

**Comment by Croydon** [comment] 2018-05-08 00:37
Might this be related to #177?

**Comment by yafp** [comment] 2018-05-08 08:00
I dont think so

At least i was not overflowing the tab-bar (no scroll bar needed) when the issue occured, which seems to be different to #177

**Comment by yafp** [comment] 2018-05-20 16:11
If it happens i get the following output in Firefoxs Browser console:

> TypeError: can't access dead object[Learn More]

from:

>   sidebar.js:266:94

**Comment by Croydon** [comment] 2018-05-20 17:58
This might be already solved or at least happening fewer times with the current dev version. I will revisit this after the 0.11.0 release.

As a temporary workaround when you run into this problem: Closing and opening the sidebar should "solve" it.

**Comment by yafp** [comment] 2018-05-20 21:36
i can confirm: your workaround (closing and opening the sidebar) helps.

**Comment by Croydon** [comment] 2018-05-26 03:44
Please let me know if this still happens with 0.11.0.

**Comment by yafp** [comment] 2018-05-28 09:35
I'll do

**Comment by Croydon** [comment] 2018-08-10 23:33
@yafp Is this still something you do encounter?

**Comment by yafp** [comment] 2018-08-21 06:45
Until now: no.

**Comment by Croydon** [comment] 2018-09-04 05:05
This might have been related to #194

Closing this because it can't be reproduced anymore.

Please report if you run into this again.

**Closed by Croydon** 2018-09-04 05:05 UTC
Labels: org:needs validation/discussion/decision
