### ISSUE TITLE
Still horizontab tabs at top when starting FF

### ISSUE THREAD

**Issue by dances-with-clouds** [Croydon/vertical-tabs-reloaded#38] opened 2016-04-11 09:14 UTC
Hello!

When FF 45 starts, for a second there's the normal horizontal tab bar at the top, but no vertical tab bar. After a second or so, the tab bar at the top disappears and the vertical tab bar is being created.

**Comment by Croydon** [comment] 2016-04-11 13:03
This is a performance problem and I am, unfortunately, not sure how much I can do about that. I will look out for possible troublemakers, but I can't promise anything.

**Comment by dances-with-clouds** [comment] 2016-04-12 11:22
Thanks for the reply! I hope you will find the troublemaker.

**Comment by woj-tek** [comment] 2016-04-15 14:06
The more tabs we have in session the more the problem is prominent, unfortunately. 
If I remember correctly this wasn't the case in older versions (tho, they have their own issues with rendering)

**Comment by Croydon** [comment] 2017-01-11 09:24
Will be solved somewhen along the road to #13.

**Comment by Croydon** [comment] 2017-04-15 18:26
No idea, while Mozilla is working on that NOW, but well, there might be performance improvements in FF55 in stuff they remove in FF57^^

https://bugzilla.mozilla.org/show_bug.cgi?id=1308332

**Comment by Croydon** [comment] 2017-04-16 22:44
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1312373 & https://bugzilla.mozilla.org/show_bug.cgi?id=1330635

There is not much I can do about it, since it's almost entirely a Firefox issue.

I will close this issue when VTR is hiding the default tabbrowser via WebExtensions APIs. This might improve the performance a bit (no animation needs to be rendered ect.), everything beyond that is out of my scope.

**Comment by grahamperrin** [comment] 2017-07-17 19:43
> … After a second or so, the tab bar at the top disappears and the vertical tab bar is being created.

I have been waiting a few minutes for the sidebar to appear. 523 tabs across eleven windows. 

The extraordinary thing about this session: 

- for my previous quit of Firefox, I allowed Session Manager to automatically restore the session. 

(When I prefer a Session Manager window (list of sessions) to appear _after_ launching Firefox, then the sidebar does appear in the one normal window that's behind the Session Manager window.)

**Comment by Croydon** [comment] 2017-08-14 04:27
With Firefox 55 this is now dramatically better. Since the major performance problem never was caused by VTR I will going to close this now. 

The performance will get even better with further Firefox/VTR versions.

**Closed by Croydon** 2017-08-14 04:27 UTC
Labels: feat:dependencies, org:in progress
