### ISSUE TITLE
No tabs listed

### ISSUE THREAD

**Issue by uroshnor23** [Croydon/vertical-tabs-reloaded#245] opened 2020-04-20 12:41 UTC
Add-on version: 0.12.1
Firefox version: 75.0 (64 bit)
OS + OS-Version: Windows 10 64 bit, 10.0.18632 Build 18362
Other tab + user interface related add-ons: None

I've been using VTR for many months with no problem; this morning I opened Firefox and the 
sidebar has the VTR heading but no tabs are listed. I attached a picture.

Thanks!

![VTRexample](https://user-images.githubusercontent.com/64016886/79752527-4ff95880-82c9-11ea-90a1-ddc459037b01.jpg)

**Comment by Croydon** [comment] 2020-04-20 15:52
I released a new version today: 0.13.0

So just to make sure: Are you actually still use version 0.12.1 or did you got updated to 0.13.0 which broke it?

**Comment by uroshnor23** [comment] 2020-04-20 16:14
I had version 0.12.1 when this happened this morning; I tried removing and reinstalling it, but it must have been before you updated it since it was still 0.12.1 then. However, I just removed it and installed the 0.13.0 version and it's still blank. I did restart Firefox but it made no difference. If you have any other suggestions, I'll be happy to try them.


Thanks!

-- MLJ


On April 20, 2020 at 8:52 AM, Croydon <notifications@github.com> wrote:






I released a new version today: 0.13.0

So just to make sure: Are you actually still use version 0.12.1 or did you got updated to 0.13.0 which broke it?

**Comment by uroshnor23** [comment] 2020-04-20 16:15
Something else I just noticed: the little buttons under the header, the plus sign and gear icon, don't do anything.


On April 20, 2020 at 9:14 AM, Mark Jeffreys <mark23@mac.com> wrote:


 I had version 0.12.1 when this happened this morning; I tried removing and reinstalling it, but it must have been before you updated it since it was still 0.12.1 then. However, I just removed it and installed the 0.13.0 version and it's still blank. I did restart Firefox but it made no difference. If you have any other suggestions, I'll be happy to try them.


Thanks!

-- MLJ


On April 20, 2020 at 8:52 AM, Croydon <notifications@github.com> wrote:






I released a new version today: 0.13.0

So just to make sure: Are you actually still use version 0.12.1 or did you got updated to 0.13.0 which broke it?

**Comment by Croydon** [comment] 2020-04-20 16:48
New versions always have the chance for new problems, but when this started to happen with the 0.12.1 version that it might not be directly related to VTR.

Did you change any Firefox settings? Install, enabled any other add-on?

Or did you change VTR settings?

**Comment by Croydon** [comment] 2020-04-20 16:50
Or another random idea: Did you open any tabs with non-ascii characters/special characters/html within it's title or anything like that? There were escaping problems in the past

**Comment by uroshnor23** [comment] 2020-04-20 18:31
No, I didn't make any changes to any of those. It was working fine last night when I went to bed, but when I opened Firefox this morning it wasn't working. I only use a few extensions other than VTR: Adblock Plus, iCloud Bookmarks and Sticky Password. I removed all of them, added back VTR by itself before I added the others and it is still blank (it was also blank when I only had VTR installed).



And I can see no special characters in any of the tab names; I opened a new window with just one tab and VTR was still blank in that window.



Thanks for your assistance,

-- MLJ


On April 20, 2020 at 9:48 AM, Croydon <notifications@github.com> wrote:






New versions always have the chance for new problems, but when this started to happen with the 0.12.1 version that it might not be directly related to VTR.

Did you change any Firefox settings? Install, enabled any other add-on?

Or did you change VTR settings?

**Comment by Croydon** [comment] 2020-04-20 18:55
This is weird. I'm not sure how to debug this or reproduce this yet.

  * Did Firefox update itself?
  * Do you have any Firefox Studies running? You can see them under `about:studies`
  * Are you familiar with the Firefox Browser Console?

**Comment by uroshnor23** [comment] 2020-04-20 19:42
If I recall correctly, Firefox last updated several days ago; I'm on version 75.0 (64 bit). The about:studies list shows 2 completed studies but no active ones. And I do know about the console though I haven't used it in a long time. (Before I retired I used to be the programmer and analyst for a department of a major financial firm.) I brought it up -- even remembered the key combo :) -- if you want me to check something.


On April 20, 2020 at 11:55 AM, Croydon <notifications@github.com> wrote:






This is weird. I'm not sure how to debug this or reproduce this yet.

Did Firefox update itself?
Do you have any Firefox Studies running? You can see them under about:studies
Are you familiar with the Firefox Browser Console?

**Comment by uroshnor23** [comment] 2020-04-21 16:11
So I was having a couple of other different but still odd problems with extensions: Sticky Password and AdBlock Plus were giving me odd messages when I opened Firefox. So I decided to uninstall and reinstall Firefox. I did that and VTR was there and working when I launched it. Weirdly, I'm still getting the Sticky Password and AdBlock Plus messages, but VTR is good to go. Which is great, since I hadn't realized how much I relied on it until it wasn't there :)


Thanks for your help,

-- MLJ


On April 20, 2020 at 12:42 PM, Mark Jeffreys <mark23@mac.com> wrote:


If I recall correctly, Firefox last updated several days ago; I'm on version 75.0 (64 bit). The about:studies list shows 2 completed studies but no active ones. And I do know about the console though I haven't used it in a long time. (Before I retired I used to be the programmer and analyst for a department of a major financial firm.) I brought it up -- even remembered the key combo :) -- if you want me to check something.


On April 20, 2020 at 11:55 AM, Croydon <notifications@github.com> wrote:






This is weird. I'm not sure how to debug this or reproduce this yet.

Did Firefox update itself?
Do you have any Firefox Studies running? You can see them under about:studies
Are you familiar with the Firefox Browser Console?

**Comment by Croydon** [comment] 2020-04-21 18:11
Sorry for your troubles. I hope that the other add-ons will start to work again too

For now, I guess I can close this issue as `invalid`, since it does not seem to be related to VTR.

If you should ever find the reason for this behaviour it would be great if you could report back. This might help other people who run into this problem as well.

**Closed by Croydon** 2020-04-21 18:11 UTC
Labels: org:needs validation/discussion/decision
