### ISSUE TITLE
Opening new tab while tabbar hidden

### ISSUE THREAD

**Issue by AmauryLiet** [Croydon/vertical-tabs-reloaded#79] opened 2017-02-07 12:50 UTC
_Add-on version: 0.8.0
Firefox version: 51.0.1 (64-bit)
OS + OS-Version: Windows10 64-bit
Other tab + user interface related add-ons: <None>_

First thanks **A LOT** for the amazing addon, my average 50 tabs and I wouldn't survive without it.

I noticed that VTR is facing an issue when I open a new tab while the tabbar is hidden.

**How to re-create the issue:**
1-Go to any page
2-Hide the tabbar
3-Open a new tab (both 'ctrl+t' and 'file>new tab' cause the bug)
4-Type something in the url bar and press enter

**The issue:**
A new tab is indeed created and displayed ('about:blank' or equivalent is showed), but the url/search is loaded in the previous tab (overriding it).
When showing back the tabbar, no tab seems to be selected (neither the New Tab nor the previous one)

**Comment by Croydon** [comment] 2017-02-07 20:53
Thanks for using VTR :)

This is a duplicate of #42.

**Closed by Croydon** 2017-02-07 20:53 UTC
