### ISSUE TITLE
Pinned tabs don't stay at the top if you have enough tabs to scroll

### ISSUE THREAD

**Issue by justdave** [Croydon/vertical-tabs-reloaded#113] opened 2017-08-15 19:41 UTC
Add-on version: 0.8.4.1
Firefox version: 56.0b2
OS + OS-Version: Mac OS X 10.12.6
Other tab + user interface related add-ons: Tab Groups

Pinned tabs appear to be part of the scroll region of the tab bar, which means if you have enough tabs to make your tab bar scroll, they scroll off the top when you scroll down.  This kind of defeats the purpose of having them pinned.  Pinned tabs should be outside the scroll region so they're locked in place on the tab bar, regardless of scrolling (probably with its own scroll region and a maximum size based on the percentage of the window size in case someone's an idiot and pins a billion tabs).

**Comment by Croydon** [comment] 2017-08-15 20:11
Duplicate of #2.

More information at 
https://github.com/Croydon/vertical-tabs-reloaded/issues/2#issuecomment-298379563 and #13.

This will be fixed with the new WebExtension sidebar, there won't be a fix for the current legacy one. Please be patient.

**Closed by Croydon** 2017-08-15 20:11 UTC

**Comment by justdave** [comment] 2017-08-15 20:36
Aha! awesome.  Thanks!
