### ISSUE TITLE
Not work on 55.0a1

### ISSUE THREAD

**Issue by KuoE0** [Croydon/vertical-tabs-reloaded#84] opened 2017-04-24 03:03 UTC
Add-on version: 0.8.2
Firefox version: 55.0a1
OS + OS-Version: macOS 10.12.4
Other tab + user interface related add-ons: 
- Close Tab By Double Click
- Omnibar

**Comment by Croydon** [comment] 2017-04-24 06:21
Please use the search before reporting issues.

This is a duplicate of #83

**Closed by Croydon** 2017-04-24 06:21 UTC
