### ISSUE TITLE
[feature request] Almost mandatory: Implement tab containers

### ISSUE THREAD

**Issue by hipunk** [Croydon/vertical-tabs-reloaded#179] opened 2018-04-08 07:27 UTC
Add-on version: Latest (doesn't really matter)
Firefox version: Latest (doesn't really matter)
OS + OS-Version: Latest (doesn't really matter)
Other tab + user interface related add-ons: Lots (doesn't really matter)

Hi,

tab containers matured from an addon into an integrated feature of firefox since a few versions.
It would be very, very useful to have this functionality supported in vtr by underlining the tab title with the corresponding color of the container just like in the tab bar.

Greetz,

hipunk

**Comment by Croydon** [comment] 2018-04-08 07:34
Please use the search before reporting issues.

This is a duplicate of #92.

**Closed by Croydon** 2018-04-08 07:34 UTC
