### ISSUE TITLE
Hotkey to hide bar only works in the latest opened window

### ISSUE THREAD

**Issue by mbaz** [Croydon/vertical-tabs-reloaded#30] opened 2016-03-29 01:10 UTC
When typing the hotkeys to hide the tabbar, nothing happens. I tried changing the keys to control-shift-b with the same result.

Running 0.4.0 on Firefox 45, Arch Linux.

**Comment by Croydon** [comment] 2016-03-29 14:08
I can't reproduce this. Anybody else who have this problem?

@mbaz Could you please try to temporary disable all other add-ons, then restarting Firefox and try it again?

**Comment by Croydon** [comment] 2016-03-29 14:20
It seems to only work in the latest opened window. Is this the source of your problem?

**Comment by mbaz** [comment] 2016-03-29 23:24
I just tried with a new profile. Indeed, it seems to work only on the latest opened window. I may have missed that in my regular setup, where I have six windows open.

**Comment by yafp** [comment] 2016-03-30 06:37
i can reproduce this bug.

How i was able to reproduce:
- Open FF window 1 -> shortcut works in window 1
- Open FF window 2 -> shortcut works in window 2
- Switch focus to FF window 1 -> shortcut doesnt work in window 1 but instead in the non-active window 2

**Comment by Croydon** [comment] 2016-04-17 14:03
@mbaz Will be fixed with the next update :)

**Closed** 2016-04-17 14:03 UTC
Labels: bug
