### ISSUE TITLE
With VTR 0.8.2 the Firefox title windows is missing.

### ISSUE THREAD

**Issue by santonino1984** [Croydon/vertical-tabs-reloaded#82] opened 2017-04-03 14:23 UTC
Add-on version: Vertical Tab Relodaded 0.8.2
Firefox version: 52.0.1 (64 bit)
OS + OS-Version: Microsoft Windows 7 Pofessional (64 bit)

I installed the recent 0.8.2 version of VTR and the title bar was missing, then I used the "safe mode" from Firefox and then without any active extension I see again the title bar window, and then restarted Firefox and tried with four to six extensions activated (and the rest of the extensions deactivated) every time until all the extensions except VTR were active, and the title bar windows appeared correctly, but then the VTR extension was activated and then the title bar windows was missing again.

Then all the extensions were manually deactivated, except VTR and then again the title bar windows was missing.

In a clean installation of Mozilla Firefox 52.0.1, I installed only the VTR 0.8.2 and the title bar window was missing, that's was with a clean profile without any historial of extensions or themes installed, so your VTR extension doesn't had any conflict with other extensions.

Then I installed a VTR old version, the 0.7.1 in my full firefox profile, and now I have again the title bar windows appearing correctly in the top of the Firefox windows (with the title of the active tab) with all the others extensions active.

For now I am using the VTR version 0.7.1 and everything is correct, so you can compare the two extension (0.7.1 vs 0.8.2) to see where is the bug, thanks,

Sergio

********************************
EXTENSION LIST INSTALLED IN MY FULL MOZILLA FIREFOX 52.0.1:

Aplicación: Firefox 52.0.1 (20170316213829)
Sistema Operativo: WINNT (x86_64-msvc)

- AdBlocker for YouTube™ Video 0.1.5
- Administrador de sesiones 0.8.1.13
- Application Update Service Helper 2.0
- Auto Unload Tab 0.9.1.5
- BetterPrivacy 1.77
- Classic Theme Restorer 1.6.4
- Classic Toolbar Buttons 1.5.5
- Clean Links 2.7.1-signed.1-signed
- Cookie Import/Export 1.0.1
- Copy Links 0.1.7.1-signed.1-signed
- Dictionary Switcher 1.3.3.1-signed.1-signed
- Download Status Bar 15.0.0.1
- DownThemAll! 3.0.8
- Duplicate Tabs Closer 2.2.5
- Empty Cache Button 2.7.1-signed.1-signed
- Extension List Dumper 2 1.0.2
- FireShot Pro 0.98.90
- Flash Control 2.1.4
- Forecastfox (fix version) 2.4.8
- FoxClocks 4.2.3
- Gmail Manager-community 0.7.1.2
- Greasemonkey 3.10
- HTTPS Everywhere 5.2.13
- Image Picker 1.9.5
- Linkificator 2.3.2
- Menu Filter 19.1
- Multi-process staged rollout 1.9
- NoScript 5.0.2
- OneTab 1.17.0
- Password Exporter 1.3.3
- Pocket 1.0.5
- Privacy Badger 1.9.2
- Reader 52.0
- Resurrect Pages 3
- Right Links 0.4.0
- Secure Login 1.2.5
- Secure Login (WebExtension) 0.1.6 (Inactivo)
- Self-Destructing Cookies 0.4.12
- Status-4-Evar 2016.10.11.01
- Tab Mix Plus 0.5.0.2
- Textarea Cache 0.9.3.4
- Toggle animated GIFs 1.3.1
- uBlock Origin 1.11.4
- URL Lister 1.3.1-signed.1-signed
- Vertical Tabs Reloaded 0.7.1
- Video DownloadHelper 6.2.0
- Visited 1.13.1
- Web Compat 1.0
********************************

**Comment by Croydon** [comment] 2017-04-03 15:55
> In a clean installation of Mozilla Firefox 52.0.1, I installed only the VTR 0.8.2 and the title bar window was missing, that's was with a clean profile without any historial of extensions or themes installed, so your VTR extension doesn't had any conflict with other extensions.

The title bar is getting hidden once at add-on installation, after the installation it's up to the user (via the toggle button or about:config) or to other add-ons if the title bar is getting display or hidden.

In your clean Firefox profile, where you have nothing but VTR installed, can you succesful toggle the titlebar?

**Comment by santonino1984** [comment] 2017-04-03 17:05
OK, now I tried the toggle button in the last clean Firefox installation and the title bar was missing after, but now I tried a second clean Firefox installation (deleted the first) and now the title bar is present with the VTR 8.0.2 without need to use the toggle button, so this is random? the only sure thing is, in my normal Firefox installation, VTR 8.0.2 disappears the title bar and the toggle button is broken, but if I downgrade to VTR 0.7.1 then everything is fine with the title bar present.

Both the clean Firefox installation and my normal installation are the same version 52.0.1, and I use Firefox portable, so is easy to backup the one portable folder and make tests, and restore the backed folder after that.

The other sure thing is, your extension is compatible with every extension in my Firefox installation, in my last message you will see the tests I made to confirm where was the issue, so is a possible bug in VTR but I don't know if its randomness; I have two portable Firefox installs, in the two the title bar disappeared with VTR 8.0.2 but returned with VTR 0.7.1, I tried the other older versions of VTR 0.8.0 and 0.8.1 and the same issue with the missing title bar, so between 0.8.2 and the 0.7.1 will be the possible solution; for now I am happy with the VTR 0.7.1 in my two portable Firefox installs, cheers.

**Comment by Croydon** [comment] 2017-10-01 02:35
I'm still not able to reproduce this. However, with the full WebExtension version of VTR (v0.9.0 and later) the title bar will be completely untouched by VTR, therefore solving this issue (if it is actually caused by VTR).

@santonino1984 So if you stay on the ESR channel with FF52+v0.7.1 for now, then upgrade to the next ESR and re-enable VTR updates (don't forget that! 😉 ) it should be fine for you I guess.

Not really satisfying, but definitely a way.

**Comment by Croydon** [comment] 2017-11-02 23:22
Going to close this as invalid since I couldn't reproduce this.

**Closed by Croydon** 2017-11-02 23:22 UTC
Labels: org:needs validation/discussion/decision
