### ISSUE TITLE
Tabs don't hide in fullscreen

### ISSUE THREAD

**Issue by AndriySvyryd** [Croydon/vertical-tabs-reloaded#81] opened 2017-03-13 20:56 UTC
Add-on version: 0.8.0
Firefox version: 51.0.1 32-bit
OS + OS-Version: Windows 10 64-bit
Other tab + user interface related add-ons: Tab Mix Plus 0.5.0.2

The tabs don't hide in fullscreen if Tab Mix Plus restored previous session on startup.
Disabling and re-enabling the add-on fixes the issue until next firefox restart.

**Comment by Croydon** [comment] 2017-03-28 22:44
This sounds like some crazy XUL bug/conflict or session managemant mess.

Since all of these things will go away soon I'm not motivated to invest much time into something like this.
In an update I will publish when Firefox v55 will be released I refactored the logic when the tab browser gets hidden (d860dd8dea437ec640ebcb905a44791fcf1208c4). Bugs like these should go away then, if not it's a bug in Firefox.

For more information for the porting work to a WebExtension see #13.

Just to make sure.... you are absolutely sure that it's Tab Mix Plus causing trouble? Are you using the private mode?

**Comment by AndriySvyryd** [comment] 2017-03-29 18:44
@Croydon You are right, it actually happens without Tab Mix Plus too, just less frequently. It seems that it depends on when the tabs are restored in relation to when the addon is enabled. Usually I see the tabs created before they are arranged vertically and that's when the fullscreen issue happens.

**Comment by AndriySvyryd** [comment] 2017-03-29 18:51
Update: in 0.8.1 the "Hide tabs in fullscreen" option is not available at all 😕

**Comment by Croydon** [comment] 2017-03-29 19:21
> It seems that it depends on when the tabs are restored in relation to when the addon is enabled. Usually I see the tabs created before they are arranged vertically and that's when the fullscreen issue happens.

This is a performance issue and shouldn't cause such bugs. I have this issue by myself but fullscreen hiding works fine for me.

> Update: in 0.8.1 the "Hide tabs in fullscreen" option is not available at all 😕

Ooopps. Indeed. This bugs seems only be reproducable on the release channel of Firefox for whatever reason. I will try to fix it as soon as possible. 

The checkboxes are not getting displayed for some reason. If you click on the setting description text you can still toggle the setting.

**Comment by Croydon** [comment] 2017-03-29 19:22
> Are you using the private mode?

**Comment by AndriySvyryd** [comment] 2017-03-29 19:22
> I am not using the private mode.

**Comment by Croydon** [comment] 2017-03-29 21:12
Note to myself: The invisible checkbox bug is not happening in Firefox v53 Beta, v54 Developer Edition and v55 Nightly.

**Comment by Croydon** [comment] 2017-03-30 01:39
Note to myself: chrome://global/skin/in-content/common.css has some important differences between v52 and v53

**Comment by Croydon** [comment] 2017-03-30 01:46
@AndriySvyryd I will soon push v0.8.2 which brings the fullscreen hiding back to the state it was in v0.8.0 since it really breaks in v0.8.1 completely and the options will be displayed correctly again.

However it might not solve the situation for you right now if your fullscreen troubles have indeed other sources.

Do you mind tell me what other add-ons you have installed?

**Comment by mbaz** [comment] 2017-03-30 17:12
I just upgraded to 0.8.2 and tabs are hidden again in fullscreen.

**Comment by Croydon** [comment] 2017-04-04 16:20
@AndriySvyryd Could you please provide information if the problem is still there for you with v0.8.2?

**Comment by AndriySvyryd** [comment] 2017-04-04 16:26
@Croydon So far I haven't hit it again.

**Comment by Croydon** [comment] 2017-04-07 14:17
@AndriySvyryd Please report it again if you have issues. Closing for now.

**Comment by Croydon** [comment] 2017-04-07 14:18
b3c274118f18d475b932a38f67de02ced53104d5

**Closed by Croydon** 2017-04-07 14:18 UTC
Labels: org:needs validation/discussion
