### ISSUE TITLE
Tab font/fontsize changed to too small when updated to FFOX 64.0

### ISSUE THREAD

**Issue by Ironizer** [Croydon/vertical-tabs-reloaded#216] opened 2018-12-12 09:26 UTC
Add-on version: 0.12.0
Firefox version: 64.0
OS + OS-Version: Win7 SP1

I just updated FFOX to 64.0 from 63.x, and the font and/or size of the font changed on the tabs, especially on the inactive tabs, the text became very small.
![2018-12-12_10-24-29](https://user-images.githubusercontent.com/45816027/49859589-305e4000-fdf8-11e8-9ec4-0a3d987dd7a0.png)

**Comment by Croydon** [comment] 2018-12-12 11:57
I'm not sure why there should be a font size difference between FF 63 and 64 and I also can't reproduce it on Windows 10. Highly speculative: Maybe FF did change some styling which effects your configuration and not mine.

However, in it's core your want bigger font sizes so I'm going to close this as a duplicate of #195. 
0.13.0 will bring bigger font sizes and some future update will make the font sizes configurable.

**Closed by Croydon** 2018-12-12 11:57 UTC
