### ISSUE TITLE
0.8.4-alpha: if the tabs sidebar is hidden when a link is opened in a new tab, then there will be problems (primarily title and URL) with multiple tabs

### ISSUE THREAD

**Issue by grahamperrin** [Croydon/vertical-tabs-reloaded#105] opened 2017-07-16 07:05 UTC
## Steps

1. at any page that includes a link 
2. click the VTR button
3. observe disappearance of the sidebar
4. open the link in a new tab

## Expected

- for the new tab, a visibly correct title and URL
- normal behaviour when using keyboard shortcuts to navigate between tabs

## Actual results

`5.` either (a) use a keyboard shortcut (e.g. Control-Page Down on FreeBSD), or (b) click the VTR button to reveal the sidebar then click on the new tab

- in the title bar, the title of the previous tab
- in the awesome bar, the URL of the previous tab
- in the tabs sidebar, a favicon but no title

### Caution

If you close a new tab that is bugged as described above, then Firefox may cease to render a previously opened tab. (That happened to me whilst drafting this issue.)

## Environment

0.8.4-alpha

No other extension. 

Firefox 54.0.1 (64-bit) 
```text
$ date ; uname -n ; uname -v
Sun Jul 16 07:43:38 BST 2017
momh167-gjp4-macbookpro82-freebsd
FreeBSD 12.0-CURRENT #0 r320599: Mon Jul  3 15:34:15 UTC 2017     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC 
$ 
```

----

If I recall correctly, this issue was first seen with 0.8.4-alpha on Firefox 55.x (32-bit) on Kubuntu.

**Comment by grahamperrin** [comment] 2017-07-16 07:08
https://github.com/Croydon/vertical-tabs-reloaded/commit/8f72143ef736f6a579d02ccd595d166743b456f1 was _Add toolbar button to toggle sidebar_.

**Comment by grahamperrin** [comment] 2017-07-16 07:24
A long shot, I wondered whether e10s is a factor. 

Not so. I changed `browser.tabs.remote.autostart.2` from true to false, restarted Firefox and reproduced the issue.

**Comment by Croydon** [comment] 2017-07-16 15:03
Thanks for reporting, but this is a duplicate of #42.

**Closed by Croydon** 2017-07-16 15:03 UTC

**Comment by grahamperrin** [comment] 2017-07-16 15:31
Thanks. (I did browse issues before reporting, but didn't equate the phrase _tabbar_ with _sidebar_. A bit dyslexic here.)
