### ISSUE TITLE
Tab close button looks a bit strange. Seems overlapped with another icon.

### ISSUE THREAD

**Issue by juliohm1978** [Croydon/vertical-tabs-reloaded#101] opened 2017-06-18 02:14 UTC
Add-on version: 0.8.3.1
Firefox version: 53.0.3 (64-bit)
OS + OS-Version: Linux Mint 18.1 Serena
Other tab + user interface related add-ons: 

Looking at the vertical tabs, the icon for closing the tab seems overlapped with another image. Below is an example:

![selection_002](https://user-images.githubusercontent.com/4145456/27257599-b9667558-53b2-11e7-9cea-bd23dbd23ef2.png)

**Comment by mrowwy** [comment] 2017-07-05 15:37
I'm also seeing something similar.
![2017-07-05_08h35_39](https://user-images.githubusercontent.com/1996611/27872254-0505ceb6-615d-11e7-8da8-b176830be379.png)

VTR: 0.8.3.1
FF: 54.0.1
OS: W10

**Comment by grahamperrin** [comment] 2017-07-18 05:00
I see this issue with at least one theme after the extension is added. 

In my case, the workaround seems to be a restart. Firefox 54.0.1 (64-bit) on KDE Plasma 5 on FreeBSD-CURRENT. 

I currently prefer the Darwin theme, with the close box to the left of the favicon.

**Comment by grahamperrin** [comment] 2017-07-25 17:05
With Vertical Tabs Reloaded 0.8.4-alpha alone, I can reproduce the symptom by switching from _Darwin_ to _Dark (recommended)_: 

![2017-07-25 18 00 13](https://user-images.githubusercontent.com/192271/28584188-ae6f4818-7163-11e7-921b-aa6f13733631.png)

![2017-07-25 18 01 59](https://user-images.githubusercontent.com/192271/28584197-b7628340-7163-11e7-928b-4f2f7fb50521.png)

**Comment by fungs** [comment] 2017-07-27 08:34
Mine look like @mrowwy's but are stretched horizontally after installation (widescreen resolution?). However, restart fixes the issue.

**Comment by Croydon** [comment] 2017-09-15 00:23
For the dark theme this should be fixed with b1d8203a838dd879abe41868a1fe0b11e8e40880  (will be in the next update). For the rest of the themes I will introduce the fix when rewriting them for the full WebExtension version.

**Comment by coolynx** [comment] 2017-09-28 16:59
Thanks guys for extension. Just upgraded my Firefox 56.0 and found out that this is THE version where Tab Center stopped working. 😢 

Suggested Tab Center Redux does not work with Group Tabs.

So, I found this one. 👍 

Guessed that it should have a close button. By clicking in the area tabs were closed but without a button. 😄 

<img width="306" alt="screenshot 2017-09-28 at 19 51 58" src="https://user-images.githubusercontent.com/5902951/30979619-dd678990-a486-11e7-894a-8c3cd4d5a883.png">

VTR: 0.8.4.1
Firefox 56.0
OS: OS X El Capitan 10.11.6

**Comment by coolynx** [comment] 2017-09-28 17:25
After playing around and restarting Firefox few times I got a close button. So, there are no issue with the latest Firefox 56.0 and extension. 👍 

<img width="267" alt="screenshot 2017-09-28 at 20 23 27" src="https://user-images.githubusercontent.com/5902951/30980814-01218666-a48b-11e7-94cc-ab1a52505e61.png">

Sorry to spam this thread.

**Comment by Croydon** [comment] 2017-11-02 23:19
Well, the close button still causes problems (like #132), but the problem in this form is solved.

**Closed by Croydon** 2017-11-02 23:19 UTC
Labels: cat:bug, feat:themes, org:in progress
