### ISSUE TITLE
[FEATURE REQUEST] Pinned tabs as icon only (options)

### ISSUE THREAD

**Issue by as3mbus** [Croydon/vertical-tabs-reloaded#228] opened 2019-04-27 07:07 UTC
Add-on version: 0.12.1
Firefox version: 66.0.3
OS + OS-Version: Arch Linux
Other tab + user interface related add-ons: many.

hey i just found out this plugin and it seems really neat. well i alrdy do found tree style tab which also do this. but for the time being i'd like to avoid tree style tab just because it conflict with simple tab group plugin lately and i dont really use the tree style feature most of the time.

Just a feature request from Ex-TST user, it would be nice to have pinned tab only display icon
instead of hogging several tab view. just like normal horizontal tab view. this displayed p nicely in TST, so i would love if that could be implemented here as well. if you are unsure to add this feature as default could you add it as an option. 

thank you for reading this issue and great job with the extension

**Comment by Croydon** [comment] 2019-04-27 09:22
This is a duplicate of #20

In the current stable release you can already enable it https://github.com/Croydon/vertical-tabs-reloaded/issues/20#issuecomment-445527029

it will be promoted to a stable feature in 0.13.0 

Thanks for the compliments 😄

**Closed by Croydon** 2019-04-27 09:22 UTC
