### ISSUE TITLE
Pin tabs with/without text 

### ISSUE THREAD

**Issue by lootninja77** [Croydon/vertical-tabs-reloaded#121] opened 2017-09-13 02:52 UTC
Add-on version: 0.8.4.1
Firefox version: Waterfox 55.0.2
OS + OS-Version: Windows 10
Other tab + user interface related add-ons: 

Noticed behavior: When there are not enough tabs to cause a scroll bar, text labels show on pinned tabs. Once you open enough tabs to have a scroll-bar, the text labels disappear. 

Desired behavior: always show the text labels for pin tabs, or have the ability to toggle weather or not they show in options.

**Comment by Croydon** [comment] 2017-09-24 13:37
That pinned tabs don't have a text label sometimes is actually a bug and not intended.
There won't be a fix for the legacy sidebar anymore, but it will be fixed in the new WebExtension sidebar. Pinned tabs are already better implemented there (always visible at top). Also at some point I will implement this feature: #20, which only shows the favicon of the pinned tab and no text.

So the short answer is: Please be patient :)

**Comment by Croydon** [comment] 2017-11-02 23:17
Closing as duplicate of #20.

**Closed by Croydon** 2017-11-02 23:17 UTC
Labels: cat:bug, cat:CRITICAL, feat:core, org:duplicate, org:in progress
