### ISSUE TITLE
New tabs do not open correctly, when the tabbar is hidden.

### ISSUE THREAD

**Issue by danwep** [Croydon/vertical-tabs-reloaded#42] opened 2016-05-20 19:57 UTC
Add-on version: 0.6.1
Firefox version: 46.0.1
OS + OS-Version: Linux, Debian testing[codename stretch]

When using the hotkey for hiding/showing the tabbar and the tabbar is
hidden. New tabs do not open correctly. The tab name is not displayed on
the tab and can not close the tabs. Also even after showing the tabbar again,
new tabs still do not open correctly. The only way to fix these issues is to
restart Firefox.

The first screenshot, shows new tabs not opening correctly. And the
second screenshot, shows the tabs as they should be displayed; after
restarting Firefox. The only add-on installed was VTR, in a new profile
to avoid any conflicts with other add-ons and/or user settings.

![firefox-bad-tabs-2016-05-19-160204_1920x1162_scrot](https://cloud.githubusercontent.com/assets/19493113/15440038/39b71980-1ea1-11e6-810e-966a9ca854db.png)

![firefox-after-restart-2016-05-19-160304_1920x1162_scrot](https://cloud.githubusercontent.com/assets/19493113/15440037/39b32820-1ea1-11e6-9c9e-0073bed585e0.png)

Thank You for this add-on, which just found recently. Much better than
others that have tried in the past and not having tree style tabs.

**Comment by Croydon** [comment] 2017-02-07 20:54
Note to myself: Firefox is unloading certain events when the respective UI elements are getting hidden. This is likely the cause of this bug.

**Comment by Croydon** [comment] 2017-03-21 23:04
Will be fixed somehow, somewhen by porting to WebExt. #13

**Comment by Croydon** [comment] 2017-04-03 16:02
This will be fixed with https://bugzilla.mozilla.org/show_bug.cgi?id=1332447

**Comment by grahamperrin** [comment] 2017-09-01 05:10
Mozilla bug 1332447 (above) is _WebExtension API to hide the tabstrip_. 

There's also [1341126 - add open API to browser/page/sidebarAction](https://bugzilla.mozilla.org/show_bug.cgi?id=1341126) (WebExtensions frontend), which is:

>  RESOLVED FIXED in Firefox … 

… 57. 

I'm pleased that 1341126 is fixed, but the association with 57 sort of dashes my hope that this critical issue #42 might somehow be fixed for users of an inferior version of Firefox. 

----

This (42) rarely bugs me, because I rarely open new tabs in full-screen mode, but since critical full-screen issue #110 is fixed (0.8.5-alpha ), there seems to be a slightly increased risk of 42 biting …

**Comment by grahamperrin** [comment] 2017-10-12 03:05
Partly in response to https://matrix.to/#/!xAcrCyjpCWOtluwgSS:matrix.org/$1507765477330816mWgia:matrix.org

Unfortunately my (OBS) screen recordings do not capture mouse clicks, but I'm almost certain that in this frame (for example) there _was_ a click on the 'close' icon (2017-10-11 at 02:39:43): 

![2017-10-11 02 39 43 frame](https://user-images.githubusercontent.com/192271/31476924-efc635d0-af00-11e7-9621-7befb99ba43e.png)

– but then the tab did not close, and so on. 

The misbehaviours involving that 'New Tab' were, in some ways, reminiscent of the misbehaviours that can occur if this bug #42 is either unknown or forgotten before the sidebar (sorry, maybe I should say _tab bar_) is hidden. 

Comparable misbehaviours, but I'm almost certain that there was **no hiding of the bar** before that 2017-10-11 incident. That level of certainty is because knowing this bug #42, my hiding of the bar is extremely rare; reserved for very special occasions. 

----

What's above is thrown into this issue only in case it helps to understand the possible cause(s) of this bug.

**Comment by grahamperrin** [comment] 2017-10-19 06:03
>>> … [**when the tabbar is hidden.**](https://github.com/Croydon/vertical-tabs-reloaded/issues/42#show_issue)

>> [Note  to myself: Firefox is unloading certain events when the respective UI elements are getting hidden. This is likely the cause of this bug.](https://github.com/Croydon/vertical-tabs-reloaded/issues/42#issuecomment-278136877)

> … [_almost_ certain that there was **no hiding of the bar**](https://github.com/Croydon/vertical-tabs-reloaded/issues/42#issuecomment-336007695) …

Now, with Vertical Tabs Reloaded 0.8.5.2 and Firefox 56.0.1 (64-bit) on FreeBSD-CURRENT: 

a) I'm _certain_ that the symptoms in this issue can be triggered whilst the user's preference is to show (not hide) the bar; and 

b) where e.g. [Session Manager](https://addons.mozilla.org/addon/session-manager/) is used, a consequence of this issue 42 may be **incomplete session information** saved at quit time (whilst the quit may _appear_ to be smooth and crash-free, the subsequent launch may present a crash recovery dialogue that lacks most of what was present at quit time). 

In this screenshot, tab mishandling began after I dragged a tab from [SeaMonkey Vertical Tab Bar](https://addons.mozilla.org/seamonkey/addon/seamonkey-vertical-tab-bar/) 1.0, dropped around the foot of the sidebar of Vertical Tabs Reloaded: 

![2017-10-19 03 30 10](https://user-images.githubusercontent.com/192271/31755401-20d4c98a-b496-11e7-888d-b9dd2ae7e767.png)

Consequences from a (Session Manager) crash recovery perspective: 

![2017-10-19 03 42 52 session manager - mozilla firefox](https://user-images.githubusercontent.com/192271/31755440-64cf59f2-b496-11e7-9ba9-d8e502e0ab72.png)

![2017-10-19 03 46 49](https://user-images.githubusercontent.com/192271/31755439-64a8de8a-b496-11e7-8d00-6e356e191f53.png)

(Loosely speaking: with the most recent crash, ten of fourteen windows were missing from the recovery file; with the prior crash, thirteen of fourteen were missing. Such extreme losses will be avoidable – now, I allow Session Manager to perform periodic backups, every few minutes.)

**Not** easily reproducible: 

![2017-10-19 04 46](https://user-images.githubusercontent.com/192271/31755856-9bc30628-b498-11e7-8877-8f33f77edffc.gif)
[2017-10-19 04:46.ogv.zip](https://github.com/Croydon/vertical-tabs-reloaded/files/1397212/2017-10-19.04.46.ogv.zip)

I'm toying with the possibility that in my case, the bug can occur with the sidebar present only where a session involved a rename, removal or addition of a group (re: the first screenshot in this comment, I _had_ added a 'Firefox Quantum Flow' group to the window that contains the 'Firefox' group, and it was necessary to recreate and repopulate that group after the crash). More than that, however, I'm mindful of the February comment about hiding of **respective UI elements** …

----

Given the focus on WebExtensions APIs and Firefox 57, I don't expect a fix to target this 'legacy' sidebar.

**Comment by Croydon** [comment] 2017-11-02 23:24
Will not happen with the WebExtension version (v0.9.0), does already not happening anymore in the developer versions (starting with v0.8.6).

Will land in release not later than Nov 14.

**Closed by Croydon** 2017-11-02 23:24 UTC
Labels: cat:bug, cat:CRITICAL, feat:dependencies, org:in progress

**Comment by grahamperrin** [comment] 2017-11-06 01:12
OK 👍 

I expect to use 56.x until the [August 2018 release of Firefox 62](https://wiki.mozilla.org/RapidRelease/Calendar#Future_branch_dates). With what's below, I have more than enough to make this bug with legacy Vertical Tabs Reloaded ❤️ (in use with Tab Groups ❤️ and other legacy extensions) _extremely_ rare for me ☑️ 

----

By coincidence today I captured, whilst recording the screen, what I believe is the bug. 

>> … [Firefox is unloading certain events when the respective UI elements are getting hidden. This is likely the cause of this bug.](https://github.com/Croydon/vertical-tabs-reloaded/issues/42#issuecomment-278136877)

> [a) I'm certain that the symptoms in this issue can be triggered whilst the user's preference is to show (not hide) the bar](https://github.com/Croydon/vertical-tabs-reloaded/issues/42#issuecomment-337808303); and
> 
> b) where e.g. Session Manager is used, a consequence of this issue 42 may be incomplete session information saved at quit time …

## For reference

### [Forcing Firefox into a situation that will cause loss of session restoration data](https://www.youtube.com/watch?v=hYYEowNZH3I)

> … begin to make the bug reproducible some time after 03:51 on the timeline. There's bug-free closure of a tab that was opened by using the button of Firefox Lightbeam in the Australis menu of Firefox. 
> 
> Around 04:24 there's attempted closure of a similarly opened tab. Firefox can not close the tab. Note the positioning of the window of Firefox, partly obscured (by a panel of KDE Plasma 5). 
> 
> 04:50 the predicted consequent failure of Firefox to work with Session Manager.

**Comment by grahamperrin** [comment] 2018-06-01 16:08
For reference only, a very brief summary of one of the easy ways in which this bug will bite: 

1. visit https://github.com/Croydon/vertical-tabs-reloaded/issues/166#issuecomment-393717617
2. toggle tab sidebar (click the VTR icon)
3. <kbd>Control</kbd>-<kbd>T</kbd> or use the **File** menu to open a new tab
4. <kbd>Control</kbd>-<kbd>W</kbd>
5. again, toggle tab sidebar. 

Expected: 

- closure of the new tab, a view of issue 166 and a normal sidebar

Actual reult: 

- closure of the wrong tab, a wrong view of a page and an abnormal sidebar. 

Depending on what you do after that, things can quickly become too weird.  

## Some screenshots

![2018-06-01 16 50 39 please maintain a version for waterfox issue -166 croydon-vertical-tabs-reloaded github - waterfox](https://user-images.githubusercontent.com/192271/40850911-c647d42e-65bd-11e8-9979-29d9b2e8525b.png)

![2018-06-01 16 52 12 please maintain a version for waterfox issue -166 croydon-vertical-tabs-reloaded github - waterfox](https://user-images.githubusercontent.com/192271/40850931-d32b5f94-65bd-11e8-9473-f98bcd17ebd9.png)

![2018-06-01 16 55 10 please maintain a version for waterfox issue -166 croydon-vertical-tabs-reloaded github - waterfox](https://user-images.githubusercontent.com/192271/40850956-dcc62796-65bd-11e8-8fed-a86c5be74c01.png)

– note, the mismatch between new tab content, URL and title. 

With the sidebar revealed, after a few more clicks, more of a mess: 

![2018-06-01 16 56 01 please maintain a version for waterfox issue -166 croydon-vertical-tabs-reloaded github - waterfox](https://user-images.githubusercontent.com/192271/40851007-0202c424-65be-11e8-9a96-7d2de5915f42.png)
