### ISSUE TITLE
Toggle titlebar only works on one window.

### ISSUE THREAD

**Issue by xMez** [Croydon/vertical-tabs-reloaded#78] opened 2017-02-06 16:38 UTC
Add-on version: 0.80
Firefox version: 51.0.1 (64-bit)
OS + OS-Version: Windows 10 1607
Other tab + user interface related add-ons: Stylish

When using version 0.80 the toggle titlebar option only works on one window, all other windows are stuck with the tabs in the titlebar.
I can toggle the title bar from the addon menu, customize menu and about:config and it's always the same problem.
It doesn't matter what window i try to toggle from it only toggles the window that was created first, if I click a prompt that restarts firefox and all windows open at the same time(I don't have to click restore session) then I can toggle the titlebar on all of them. Any new windows created with ctrl+n are stuck with the titlebar hidden.

This bug is not present on version 0.71.

**Comment by Croydon** [comment] 2017-02-06 17:20
Sounds strongly like a Firefox bug when it's the same behaviour via about:config.
I will investigate at the weekend or next week.

@xMez Would you mind explain your user case further? Do you regularly toggle the titlebar? Or was that a rather one time thing you noticed?

**Comment by xMez** [comment] 2017-02-06 17:25
I don't usually toggle the titlebar, I noticed that when I created a new window it had the titlebar hidden even though it was set to display.

**Comment by Croydon** [comment] 2017-05-06 02:26
@xMez Would you mind retesting this with current versions of Firefox and VTR?

**Comment by xMez** [comment] 2017-05-06 11:02
Just tested with VTR 0.83 and Firefox 53.0 (64-bit).
Still have the same issue, the right window should look like the second window.
![vtr problem](https://cloud.githubusercontent.com/assets/5909610/25771804/2a1bef80-325c-11e7-9d0b-8c695df8b1a1.JPG)

**Comment by Croydon** [comment] 2017-05-06 15:08
I can reproduce this bug now.
However, this sounds like another side effect for some weird XUL thing and the impact of it is rather small.

Since I want to focus my time on #13 I'm heavily inclining to make this a WONTFIX. Once VTR is a WebExtension this bug will be gone.

**Comment by xMez** [comment] 2017-05-06 18:55
Understandable, I'll just be using an older version then until it's implemented with WebExtensions.

**Closed** 2017-05-06 19:20 UTC
Labels: cat:bug, org:wontfix
