### ISSUE TITLE
No close tabs below option.

### ISSUE THREAD

**Issue by Hotpepper00** [Croydon/vertical-tabs-reloaded#169] opened 2018-01-08 16:02 UTC
Add-on version:
Firefox version:
OS + OS-Version:
Other tab + user interface related add-ons: 

Firefox 58

The default horizontal tab bar can be hidden with a change to userchrome.css which I did, but then I discovered that there is no close tabs below (similar to close tabs to the right on the default bar). This is a feature I use a lot, any chance that this can be included in the add-on?

**Comment by Croydon** [comment] 2023-08-04 19:38
This was done with v0.10.0

This issue is also a duplicate of #120

https://github.com/Croydon/vertical-tabs-reloaded/blob/main/changelog.md#v0100-2018-03-26

**Closed by Croydon** 2023-08-04 19:38 UTC
