### ISSUE TITLE
Tab closes when single-clicking it

### ISSUE THREAD

**Issue by asampal** [Croydon/vertical-tabs-reloaded#102] opened 2017-06-19 21:48 UTC
Add-on version: 0.8.4-alpha
Firefox version: Firefox 54
OS + OS-Version: Windows 10 64 bit, Creators Update
Other tab + user interface related add-ons: Tab Mix Plus dev (0.5.0.4pre170525a1)

Since the update to Firefox 54, with VTR 0.8.4-alpha, every once in a while tabs will close when clicked on (single-click). I can bring them back using undo last tab close, but it's still quite annoying.

**Comment by asampal** [comment] 2017-06-20 13:38
I can confirm that this also happens with Nightly.

**Comment by hdelbers** [comment] 2017-07-31 06:26
I have the same problem, but only with pinned tabs. It happens more frequently with windows than with Linux.
- windows 7, firefox 54.0.1, vertical-tabs-reloaded 0.8.3.1
- Linux Mageia 6, firefox 45.5.0

**Comment by mbaz** [comment] 2017-07-31 16:01
Duplicate of https://github.com/Croydon/vertical-tabs-reloaded/issues/61 ?

**Comment by hdelbers** [comment] 2017-07-31 23:08
Probably. I found #102 when I googled.

**Comment by asampal** [comment] 2017-08-01 14:44
It's not clear to me if this is supposed to be fixed, according to the comments in #61.

**Comment by mbaz** [comment] 2017-08-01 20:42
@asampal I believe it's fixed, but in a branch that won't be merged soon.

**Comment by justdave** [comment] 2017-08-15 19:34
I'm seeing this with pinned tabs.  What it looks like to me is it's supressing the title, and the close box (which isn't visible until you hover it) is at the left right next to the icon.  Usually pinned tabs don't even have a close box, and you have to use the context menu to close it or unpin it first.

**Comment by Croydon** [comment] 2017-11-02 23:12
It will be fixed with the first full WebExtension version of VTR, which will be v0.9.0 (or any alpha version since v0.8.6).

Will be released not later than 14 Nov.

**Closed by Croydon** 2017-11-02 23:12 UTC
Labels: cat:bug
