### ISSUE TITLE
Scrolling switches tabs instead of scrolling the tab list

### ISSUE THREAD

**Issue by fbruetting** [Croydon/vertical-tabs-reloaded#47] opened 2016-05-29 01:44 UTC
Add-on version: 0.6.1
Firefox version: 46.0.1
OS + OS-Version: Fedora 23

While mouse wheel scrolling works fine, scrolling by trackpad switches tabs, instead of scrolling the tab list. The tab list gets scrolled, too, but in some weird way. Please deactivate this behaviour!

**Comment by Croydon** [comment] 2016-07-02 01:12
This seems to be a Firefox bug.

https://bugzilla.mozilla.org/show_bug.cgi?id=1192327
https://github.com/bwinton/VerticalTabs/issues/171
https://github.com/piroor/treestyletab/issues/395

**Comment by Croydon** [comment] 2017-02-03 05:38
@fbruetting This might be solved by now in Firefox. Can you still reproduce this?

**Comment by Croydon** [comment] 2017-02-03 05:38
Could by fixed by Firefox 49+

**Comment by fbruetting** [comment] 2017-02-03 18:40
No, I now use the Tab Center (you can get it through Firefox Test Pilot).

**Comment by Croydon** [comment] 2017-02-03 18:51
I'm fully aware of the Tab Center experiment, thanks.

**Closed by Croydon** 2017-02-03 18:51 UTC
Labels: cat:bug, feat:dependencies
