### ISSUE TITLE
Pinned tabs with the Darwin theme: title visibility in the sidebar

### ISSUE THREAD

**Issue by grahamperrin** [Croydon/vertical-tabs-reloaded#107] opened 2017-07-25 16:54 UTC
A minor cosmetic issue. 

## Example

1. choose Darwin 
2. pin https://www.brighton.ac.uk/about-us/index.aspx
3. restart Firefox.

The title is visible in the title bar, not (or barely) visible in the sidebar: 

![2017-07-25 17 52 14 about us - mozilla firefox](https://user-images.githubusercontent.com/192271/28583771-3f09990c-7162-11e7-981f-83a2a9c4346f.png)

## Environment

- Vertical Tabs Reloaded 0.8.4-alpha
- Firefox 54.0.1 (64-bit)
- FreeBSD-CURRENT

```text
root@momh167-gjp4-hpelitebook8570p-freebsd:~ # uname -v
FreeBSD 12.0-CURRENT #0 r320869: Mon Jul 10 13:57:55 UTC 2017     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC 
root@momh167-gjp4-hpelitebook8570p-freebsd:~ # 
```

**Comment by sabi0** [comment] 2017-09-06 09:23
I had the same issue with the Dark theme (FF 55.0.3 64-bit, Win7).
But it suddenly got fixed by itself once I cleaned up some open tabs.
Apparently pinned tabs titles disappear once a scrollbar appears in the tab pane.

**Comment by Croydon** [comment] 2017-11-02 23:03
I'm sorry, but the legacy form of the add-on won't get a fix for this anymore.

This is not a bug in the WebExtension version.

**Closed by Croydon** 2017-11-02 23:03 UTC
Labels: cat:bug, org:planned
