### ISSUE TITLE
Scrolling vertical tabs

### ISSUE THREAD

**Issue by hfrictionless** [Croydon/vertical-tabs-reloaded#23] opened 2016-03-26 06:39 UTC
Scrolling in vertical tabs sidebar changes the viewed tab. Is it possible to just scroll the content of the sidebar?

**Comment by Croydon** [comment] 2016-03-26 15:42
I can't reproduce this error. Anybody else with this problem?

@hfrictionless Could you please try to disable temporary all other add-ons and restart afterwards Firefox once to see if the error is persistent?

**Comment by woj-tek** [comment] 2016-04-10 19:31
For me scrolling on the tab-bar (on the right) causes change in the active tab... but for this is expected behaviour - majority (all?) applications changes the tab while scrolling over the tab-bar (be that vertical/horizontal)

**Comment by Croydon** [comment] 2016-07-02 01:43
This issue is very likely a duplicate of #47 and therefore a Firefox bug.
@hfrictionless do you use a trackpad?
@woj-tek Do you use also a trackpad when reproducing this?

**Comment by woj-tek** [comment] 2016-07-02 08:51
Not only - this happens both with trackpad and mouse scroll, and *for me* it's desired and I find it *very useful* :-)

**Comment by Luckz** [comment] 2016-07-19 17:44
There are extensions that add this behaviour (the mouse wheel scrolling tab selection), does it happen with this addon alone?

**Comment by Croydon** [comment] 2017-02-03 05:39
Closing as duplicate of #47. Might be fixed by Firefox 49 and newer by now.

**Closed by Croydon** 2017-02-03 05:39 UTC
Labels: org:needs validation/discussion
