### ISSUE TITLE
Feature request: drag and drop tabs from vertical bar

### ISSUE THREAD

**Issue by bojanstef** [Croydon/vertical-tabs-reloaded#282] opened 2023-11-26 20:49 UTC
Add-on version: 0.13.1
Firefox version: 119.0.1 (64-bit)
OS + OS-Version: macOS Sonoma 14.0 (23A339)

I would like to be able to drag and drop my tabs, like you can from the top bar. 

<img width="1728" alt="Screenshot 2023-11-26 at 15 45 18" src="https://github.com/Croydon/vertical-tabs-reloaded/assets/5675392/78492936-874d-428c-b615-92133de07fb6">

**Comment by Croydon** [comment] 2023-12-01 13:30
Duplicate of #142

**Closed by Croydon** 2023-12-01 13:30 UTC
Labels: org:duplicate
