### ISSUE TITLE
Small feature request/bug report

### ISSUE THREAD

**Issue by ElectricElf** [Croydon/vertical-tabs-reloaded#65] opened 2016-09-03 18:01 UTC
Add-on version: Whatever's released on Mozilla Addons as of today
Firefox version: 45.3.0
OS + OS-Version: Debian GNU/Linux Sid
Other tab + user interface related add-ons: Vimperator mainly

First and foremost, thanks SO much for bringing this extension back :) Tree-Style Tabs are okay, but way more than I need and crazy slow.

I have a small feature request/bug report/behaviour suggestion; at least on my machines (all Linux), when I'm at the last tab and I open a new tab in the background (with, say, middle-click), the vertical tabs viewport doesn't scroll down to show the newly-opened tab. I have to switch to the last tab before I see them all.

If you can't reproduce the same behaviour on your end don't worry about it - my config is crazy enough that it's entirely possible the problem is on my end.

Thanks again,

David

**Comment by mbaz** [comment] 2016-09-05 13:39
Duplicate of #53.

**Comment by ElectricElf** [comment] 2016-09-05 19:19
Oops, terribly sorry - it's been so long since I filed a bug that I didn't even think to check to see if the issue had already been reported :)

**Comment by Croydon** [comment] 2016-09-08 17:36
@ElectricElf Glad to see that you like the add-on :)

**Closed by Croydon** 2016-09-08 17:36 UTC
Labels: org:duplicate
