### ISSUE TITLE
Middle Click also brings up auto-scrolling popup

### ISSUE THREAD

**Issue by jimmyjudas** [Croydon/vertical-tabs-reloaded#234] opened 2019-11-04 10:39 UTC
When I middle click on a tab to close it, it also brings up the scrolling popup like in https://www.ghacks.net/wp-content/uploads/2014/10/mouse-auto-scroll-chrome.jpg

This doesn't happen when I middle click on a bookmark in the bookmark bar, for example. Is the VTR window not swallowing the middle click event as well as closing the tab?

Thanks

Add-on version: 0.12.1
Firefox version: 70.0
OS + OS-Version: Win 10 10.0.16299
Other tab + user interface related add-ons:

**Comment by Croydon** [comment] 2019-11-04 16:31
Thanks for reporting. Behaviour seemed to change with newer Firefox versions

**Comment by Croydon** [comment] 2020-04-20 07:04
Super weird, I can't reproduce this anymore.

@jimmyjudas Could you try again?

**Comment by baryluk** [comment] 2020-04-21 12:16
BTW. For me middle click does nothing at all. no-op. It doesn't close the tab or bring anything.

**Comment by Croydon** [comment] 2020-04-21 12:23
@baryluk  It is an opt-in feature of VTR. Did you enable tab closing on middle click?

**Comment by jiri-h** [comment] 2020-04-21 20:10
It does the same to me too, on both computers at hand. Win 8.1, FF 75.0, VTR 0.13.0 first computer, Win 10 1809, FF 68.7.0esr 64bit, VTR 0.13.0 the second computer.
Has done so since always...

**Comment by jimmyjudas** [comment] 2020-04-23 21:54
Yeah, it doesn't seem to be doing it for me now either. Currently using Firefox 75.0.

As you said, this didn't always happen and seemed to start around the time I raised the bug. Maybe Firefox introduced a bug then that they've now fixed? I'll keep an eye out for it though and let you know if it starts happening.

**Comment by yaeuge** [comment] 2020-06-23 11:25
Bug is still present. Surely, middle-button scrolling should be enabled in Firefox settings to reproduce it (Preferences -> General -> Browsing -> Use autoscrolling)

VTR 0.13.1
Firefox 77.0.1
Arch Linux

**Comment by jimmyjudas** [comment] 2020-11-18 14:30
I've started seeing this again now. It only happens when I have sufficient tabs open to make the panel scrollable. I'm not sure if that was always the case and I just didn't spot the difference between when it was/wasn't happening

**Comment by yaeuge** [comment] 2020-11-19 17:42
@jimmyjudas , I'm not familiar with JS, this solution was found at StackOverflow and seems to work. I see no risks in it, though @Croydon ignores it for some reason...

**Comment by Croydon** [comment] 2020-11-20 15:07
I'm not ignoring it I just don't have a lot of time for VTR currently

I will check out your PR for the next version (which will however not happen in 2020 anymore). It looks good on first sight

Sorry for the time being

**Comment by jimmyjudas** [comment] 2020-11-20 22:13
Thanks, Croydon. When you find the time, it'll be much appreciated ☺️

**Comment by yaeuge** [comment] 2021-06-08 22:41
BTW, switched to Sidebery extension, it is definitely worth trying

**Closed** 2023-08-04 20:51 UTC
Labels: cat:bug, feat:core

**Comment by baryluk** [comment] 2023-09-03 08:24
> @baryluk It is an opt-in feature of VTR. Did you enable tab closing on middle click?



@Croydon 

Very late reply. But I probably did not have that enabled. It was must-have feature, and I immediately uninstalled VTR, as without middle click to close tab, it was not usable for me, and I switched to Sidebary years ago.

Why it is opt-in feature? It looks like otherwise middle mouse button does not do anything else. It should be enabled by default to close the tab.
