### ISSUE TITLE
Wheel not scrolling to the top of tab-list

### ISSUE THREAD

**Issue by m0n** [Croydon/vertical-tabs-reloaded#58] opened 2016-08-06 12:25 UTC
Add-on version: 0.7.0
Firefox version: standard 47.1 or developer 50.0a2 (2016-08-06)
OS + OS-Version: Win7 x64
Other tab + user interface related add-ons: none

I having very much tabs and say that 10 pinned tabs. Wheel not scrolling to the top of tab-list if there are a pinned tab visible. I need to use scroll-bar to continue scrolling to the top of the list.

**Comment by Croydon** [comment] 2016-08-06 20:05
Duplicate of #2.

**Closed by Croydon** 2016-08-06 20:05 UTC
