### ISSUE TITLE
Add a tab search feature

### ISSUE THREAD

**Issue by smferris** [Croydon/vertical-tabs-reloaded#127] opened 2017-09-25 16:08 UTC
There's a Chrome extension called Quick Tab that has a search feature that I'd love to see added to VTR somewhere/somehow.  It works like the tab list dropdown, but adds a search field that narrows the list of tabs displayed to just the tabs with titles that match the search text.  It's very useful if you have a lot of tabs open and want to find a particular tab quickly without having to scroll through them all reading the titles to find the one you're looking for.

**Comment by Croydon** [comment] 2017-09-25 16:18
Please use the search before reporting issues.

This is a duplicate of #75

**Closed by Croydon** 2017-09-25 16:18 UTC
