### ISSUE TITLE
Plugin prevents tabs from loading while Firefox starts

### ISSUE THREAD

**Issue by M-Fabian** [Croydon/vertical-tabs-reloaded#89] opened 2017-05-04 05:15 UTC
Add-on version: 0.8.3
Firefox version: 53.0 32 bit
OS + OS-Version: Windows 7
Other tab + user interface related add-ons: none

When launching Firefox, this plugin seems to prevent tabs from loading. Without the plugin, all tabs are loaded at the same time during startup, which is what I prefer. With the plugin a tab is not loaded until I click on it.

**Comment by Croydon** [comment] 2017-05-23 09:15
This will be fixed somehow somewhen with #13.

VTR will not touch anymore at all when and how tabs are loading (except maybe requesting a reload on the behalf of the user).

**Comment by Croydon** [comment] 2017-10-30 16:46
I'm going to close this as invalid, since I'm still not sure if this is really caused by VTR in some way. I have the same behaviour actually in Nightly without any add-ons at all. Might be simply a setting or some side effect in same cases.

Since the FF57 release is two weeks away I'm not going to investigate here. If it this is caused actually by VTR it will be fixed with the v0.9 release in ca. two weeks.

**Closed by Croydon** 2017-10-30 16:46 UTC
Labels: org:invalid

**Comment by grahamperrin** [comment] 2017-11-06 17:59
Worth noting: 

- Mozilla bug [1378459 - Allow some addon functionality to load prior to any content loading](https://bugzilla.mozilla.org/show_bug.cgi?id=1378459)
