### ISSUE TITLE
Scrolling not working correctly

### ISSUE THREAD

**Issue by eeishaan** [Croydon/vertical-tabs-reloaded#98] opened 2017-05-24 16:42 UTC
Add-on version: 0.8.3.1
Firefox version: 53.0.3 (64-bit)
OS + OS-Version: macOs 10.12 (16A323)
Other tab + user interface related add-ons: Tab Groups

When I have quite a few tabs open, scrolling on the list of tabs cycles through the tabs instead of scrolling up or down the list.

**Comment by Croydon** [comment] 2017-05-24 18:45
Please use the search before reporting issues.

This is a duplicate of #47.

This behaviour isn't controlled by VTR. It will be solved by #13 since WebExtensions will be isolated.

**Closed by Croydon** 2017-05-24 18:45 UTC

**Comment by eeishaan** [comment] 2017-05-25 05:12
My bad, forgot to remove the is:open filter from search
