### ISSUE TITLE
When restarting Firefox with multiple windows, remember for each window if VTR was active or not

### ISSUE THREAD

**Issue by jpetazzo** [Croydon/vertical-tabs-reloaded#283] opened 2023-11-28 16:16 UTC
Hi!

First of all, I really appreciate the work that you did with VTR. I use it to keep all my chat platforms (Telegram, WhatsApp, Slack, etc) in a single Firefox window, and the vertical tabs are a great way to see if there is activity on any of them. So, thanks!

However, I have multiple Firefox windows; and I use VTR only on one of them. When I restart Firefox, VTR is active in all windows, and I disable it (close the vertical tab bar) on all of them, except that one window where I want it.

I was wondering if it would make sense to remember, window per window, if VTR was active or not, and restore it to the same state when Firefox restarts.

I don't know much about Firefox extensions development; I imagine/hope that it's possible to remember per-window state (as seen for instance in this [window titler extension](https://github.com/tpamula/webextension-window-titler).

Feel free to close this issue if this is not possible/out of the scope of the project; but since you invite feature ideas, I thought I'd drop that one!

Thanks either way :)

**Comment by Croydon** [comment] 2024-01-29 09:29
Thank you for your kind words!

Unfortunately, this is technically impossible to implement from my side. Firefox itself would need to remember open sidebars per window.

See also https://github.com/Croydon/vertical-tabs-reloaded/issues/260#issuecomment-1654977894

Closing as a duplicate of #260.

**Closed by Croydon** 2024-01-29 09:29 UTC
