### ISSUE TITLE
Hamburger button and X overlap

### ISSUE THREAD

**Issue by johansigfrids** [Croydon/vertical-tabs-reloaded#22] opened 2016-03-21 13:59 UTC
I just upgraded to Firefox 45 on Windows and now the hamburger menu button and the X for closing the window overlap. 

![hamburger-x-overlap](https://cloud.githubusercontent.com/assets/3668905/13920882/d61da56c-ef7d-11e5-9f00-b77ffdeaa0f7.PNG)

**Comment by heistak** [comment] 2016-03-25 02:39
Similar issue on the Mac, the top-left close/minimize/maximize buttons overlap with the toolbar.
![2016-03-25 11 38 06](https://cloud.githubusercontent.com/assets/658927/14036610/15c1f698-f27e-11e5-8baf-edbff3583efc.png)

**Comment by Croydon** [comment] 2016-03-25 14:03
This is a duplicate of #9.

@johansigfrids @heistak Please try to do what I wrote here: https://github.com/Croydon/vertical-tabs-reloaded/issues/9#issuecomment-190267470

**Closed by Croydon** 2016-03-25 14:03 UTC
