### ISSUE TITLE
nothing happens at all...

### ISSUE THREAD

**Issue by helppe** [Croydon/vertical-tabs-reloaded#50] opened 2016-06-03 18:37 UTC
Add-on version: 0.6.2
Firefox version: 46.0.1
OS + OS-Version: windows 7 pro (64 bits)

hello
when i activate this extension nothing at all happens.
so to be sure it is not a compatibility problem with an other extension i disabled all other extensions, and closed and re-opened firefox, but the tabs are still horizontally.

why?
am i the only person with this issue? and how can i fix it?

thanks

**Comment by Croydon** [comment] 2016-06-03 20:32
@helppe Is there a chance that you start Firefox in private mode? This is a know issue: #41.

If not then I will need more debug information. For example please open the Browser Konsole with Ctrl + Shift + J and copy and paste possible errors, when in doubt please provide all logs, but make sure before that it doesn't contain any kind of private information.

**Comment by helppe** [comment] 2016-06-03 22:58
OMG! you are right, it works when i disable the private mode :O !! thank you

**Comment by Croydon** [comment] 2016-06-03 23:02
@helppe If you want to use the private mode (at start up) then it works if you open a new private window. It just doesn't work in the inital private window at the momemt.

Duplicate of #41.

**Closed by Croydon** 2016-06-03 23:02 UTC
Labels: org-needs validation/discussion
