### ISSUE TITLE
Right mouse button Context Menu

### ISSUE THREAD

**Issue by loa11** [Croydon/vertical-tabs-reloaded#229] opened 2019-04-28 22:10 UTC
Add-on version: Latest I will switch it for older version
Firefox version: 66 but I will switch it back for 53 or 52 esr I cant find person with right state of mind to use last 13 versions of Firefox.
OS + OS-Version: Windows 7 and Windows 10
Other tab + user interface related add-ons: none

I would like to ask you that you give us option to use either default right mouse context menu or to get as last option in your context menu link to original context menu.
For example I need option to use close similar tabs, and If I add extension for that function, I cant use it. Also if I want to use use any extension that is mounting in the right button context menu I cant use it because your context menu doesn't show any other option than your.

Thank you.

**Comment by grahamperrin** [comment] 2020-02-22 14:26
#205

**Comment by Croydon** [comment] 2020-04-20 12:27
Duplicate of #205.

Thanks @grahamperrin!

**Closed by Croydon** 2020-04-20 12:27 UTC
