### ISSUE TITLE
Tab drop indicator is not positioned accurately

### ISSUE THREAD

**Issue by Keith94** [Croydon/vertical-tabs-reloaded#28] opened 2016-03-27 09:03 UTC
The little arrow (dropmarker) is currently buggy when dragging links onto the tab bar. It should appear in between the tabs you are dragging to.

![snag 2016 03 27 01 47 55](https://cloud.githubusercontent.com/assets/5490615/14064617/469c034e-f3be-11e5-89cb-d65904cae7b6.png)

**Comment by Croydon** [comment] 2016-03-27 15:43
Do you use the latest stable version or the latest dev version of the branch "fixstuff"? 
I can't reproduce this in the dev version.

**Comment by Keith94** [comment] 2016-03-27 18:54
I am using the latest version from "fixstuff" (via replacing files in the XPI with the updated ones)... but the drop indicator is always appearing at the very top of the tab bar, either at the left or right corners like my screenshot. Only the "Windows" theme shows a horizontal arrow while the Light+Dark+Linux use the default vertical one.

**Comment by Croydon** [comment] 2017-11-14 02:25
"Fixed" with v0.9.

Will be really fixed with #141.

**Comment by Croydon** [comment] 2017-11-14 02:26
https://github.com/Croydon/vertical-tabs-reloaded/commit/9417e34b1cc37d956c533e509010c48fe26f1bb7

**Closed by Croydon** 2017-11-14 02:25 UTC
Labels: cat:bug, feat:themes, org:planned
